### ISSUE TITLE
幅狭時に著者一覧が崩れている

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#105]
https://app.codegrid.net/author

![](https://user-images.githubusercontent.com/413984/29555010-2cfd4bea-875c-11e7-88c8-5599226df58c.png)

これはぼくがなんかやってしまった感があるな…

**Comment by geckotang** [comment]
![image](https://user-images.githubusercontent.com/683965/29556520-0eddce64-8761-11e7-9deb-56173616d7a4.png)

**Comment by myakura** [comment]
Flexboxが効いてないわけではなく（それは意図的）、`width`が`auto`になってないのが原因らしい。

https://github.com/pxgrid/codegrid-ui/blob/fd934087a5600126b78997289a167600cc308b77/src/assets2/scss/_components.scss#L4584-L4600

で、ふつうにscssをコンパイルしたらOK。

https://github.com/pxgrid/codegrid-ui/blob/fd934087a5600126b78997289a167600cc308b77/build/assets2/css/codegrid-ui.css#L6693-L6701

だけどminifierとかをかませたらだめだった。
たぶん

**Comment by myakura** [comment]
minifyしたものを展開して該当部分を抜き出した。

```css

.CG2-authorList__item {
    box-sizing: border-box;
    position: relative;
    width: calc(33% - 40px);
    min-height: 88px;
    padding: 20px 20px 30px 90px;
    border-top: 1px solid #dbdbdb;
    margin: 0 20px
}
...
@media screen and (max-width: 767px) {
    .CG2-authorList__item {
        width: auto;
        min-height: 104px;
        padding: 12px 12px 12px 100px;
        margin: 0
    }
}
...
@media screen and (max-width: 979px) {
    .CG2-authorList__item {
        width: calc(49.9% - 40px)
    }
}
```

bingo...
さてどうしようかなあ。
