### ISSUE TITLE
CG2-settingsとCG2-formProgressの幅狭時の左右marginがおかしい

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#79]
https://github.com/pxgrid/codegrid-app/issues/808 から移動。

あるべきだろう位置に配置されてなさげ。

![8960f5ae-1613-11e7-81ab-190002b89bec](https://cloud.githubusercontent.com/assets/413984/24575325/963bb4e2-16dd-11e7-8a9b-a06ad43dd5fc.png)

他にもありそうだけど、とりあえず`CG2-settings`と`CG2-formProgress`が目立つ。

**Comment by myakura** [comment]
`.CG2-container__inner`の左右のパディングを子がネガティブマージンでなんとかしようとしてるのがそもそもの問題っぽい。

```scss
.CG2-container__inner{
  box-sizing: border-box;
  max-width: 1016px;
  padding: 40px 28px;
  margin: 0 auto;
  @include max-screen( $breakpoint-middle ) {
    width: auto;
    padding: 30px 20px;
  }
}
```

```scss
.CG2-settings{
  margin: 0 -40px;
  @include max-screen( 1054px ) {
    margin: 0 -20px;
  }
  @include max-screen( $breakpoint-middle ) {
    margin: 0;
  }
}
```

```scss
.CG2-formProgress{
  font-size: 20px;
  margin: 0 -40px 60px;
  @include max-screen( 1054px ) {
    font-size: 16px;
    margin-left: -20px;
    margin-right: -20px;
  }
  @include max-screen( $breakpoint-middle ) {
    font-size: 16px;
    margin: 10px 0 20px;
  }
  // ...
}
```

`max-screen( 1054px )`なんてマジックナンバーも登場してるのでどうにかしたい。
